version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: finance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  finance-api:
    build:
      context: ./finance-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/finance-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  finance-app:
    build:
      context: ./finance-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - finance-api